### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Altai-man** [Altai-man/cro-ldap#3]
LDAP is  relatively vast, so to have The Plan we need to write it first.

Current roadmap document has to be superseded by it.

**Comment by Altai-man** [comment]
Improved with with https://github.com/Altai-man/cro-ldap/commit/43f7a44daedc5c70186c6f183d66db4a84a2673b

**Comment by Altai-man** [comment]
So as for now:

- [x] Finish with simplest commands simplest working API fleshing out.
- [x] Get LDAP URLs used by the client in place.
- [ ] We have some grammars written.
  - [ ] Write wrappers for necessary types that ensure a string is valid.
  - [x] Redo `asn-plugin` as a standalone module that patches exported types to enforce rules.
- [x] Search request
  - [x] Patch ASN::META to handle most basic recursive case(single level direct recursion) that we need to handle `Filter` type in its full form.
  - [x] Investigate usual ways to handle search request API.
  - [x] Implement client methods.
- [ ] Investigate what is missing, RFC.

**Comment by Altai-man** [comment]
~As a bonus for a weekend: writing a LDIF module.~
Already exists as Text::LDIF.

**Comment by Altai-man** [comment]
0.5 release is close, since there we are really going to just implement what is requested.
